[package]
name = "seed_entropy_blower"
authors = ["plebhash <plebhash@proton.me>"]
version = "0.1.0"
edition = "2021"

[lib]
name = "seed_entropy_blower"
path = "src/lib/mod.rs"

[dependencies]
cpal = "0.13"
bip39 = "2.0.0"
sha2 = "0.10.8"